# Generated by Django 5.1.4 on 2025-01-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(default='Customer Name', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender',
            field=models.CharField(default='Sender Name', max_length=255),
        ),
    ]
