# Generated by Django 5.1.4 on 2025-01-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
