# Generated by Django 5.1.4 on 2025-01-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
