# Generated by Django 5.1.4 on 2025-01-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_remove_invoice_balance_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
