# Generated by Django 5.1.4 on 2025-01-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoice_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
