# Generated by Django 5.1.4 on 2025-01-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_remove_invoice_sub_total_invoice_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
    ]
